### ISSUE TITLE
Asking for help about phyluce_assembly_assemblo_trinity

### ISSUE THREAD

**Issue by liugang9988** [MikeWLloyd/Utility-Scripts#1]
Hi,Mike,

I am now assembling the resequencing data (20X) into the fasta file using Phyluce pipeline. The phyluce_assembly_assemblo_trinity has been running for a long time and generating some the output. However the job failed in the middle. The error report looked like below:
###############

orm contigs using welds.
[13.4907% done]
##############
Traceback (most recent call last):
File "/n/home08/gl08/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 347, in 
main()
File "/n/home08/gl08/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 316, in main
os.makedirs(sample_dir)
File "/n/home08/gl08/.conda/envs/phyluce/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 17] File exists: '/n/scratchlfs/gl_lab/gl08/species_UCE/sample1_assembly/sample1_trinity'
###########

I wonder what it is going on? I have tried many times, but still could not make it going to the end. Could you please help to solve this?

Thank you very much .

Best wishes,

Gang

**Comment by MikeWLloyd** [comment]
@liugang9988 This issue is related to Phyluce itself, and not the scripts in this repo. 

Your issue has already been reported and resolved on the Phyluce git repo. Please see the[ issue reported here](https://github.com/faircloth-lab/phyluce/issues/90) for a similar error and resolution based on the adjustment of the `--r1-pattern` and `--r2-pattern` inputs to the `phyluce_assembly_assemblo_trinity` call you are making.

If you are running the bash scripts from this repo, adjust the `f` and `r` flags based on the suggestions provided in the issue I linked above and the bash script should run cleanly with the adjustments. 

I am closing this for now. Feel free to re-open the issue with additional details if something specific to the scripts is occurring.
